spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/cars
    username: carservice
    password: car123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

server:
  error:
    include-message: always
